version: "3.0"
services:
#  db:
#    image: mysql:5.7
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: wordpress
#      MYSQL_USER: wordpress
#      MYSQL_PASSWORD: wordpress
#    ports:
#      - "3306:3306"
#    expose:
#      - "3306"
#    networks:
#      - frontend
#
#  # phpmyadmin
#  phpmyadmin:
#    depends_on:
#      - db
#    image: phpmyadmin/phpmyadmin
#    restart: always
#    ports:
#      - '8080:80'
#    environment:
#      PMA_HOST: db
#      MYSQL_ROOT_PASSWORD: password
#      UPLOAD_LIMIT: 3000000000
#    networks:
#      - frontend

  goblog:
    build: '.'
    image: compscidr/goblog:latest
    networks:
      - frontend
    ports:
      - "7000:7000"
    expose:
      - "7000"
    volumes:
      - ../:/var/www/html/
      - ${PWD}/test.db:/go/src/github.com/compscidr/goblog/test.db
    
networks:
  frontend:
